#!/bin/sh

# Init scripts are executed with "start" argument when system boots and with "stop" argument during shutdown
# So we need to check that it's boot state, not shutdown
[ -z "$1" ] || [ "$1" == "start" ] || exit 0

source "/etc/preinit"
script_init
ls  -l "/var/lib/hakchi/rootfs/usr/share/games" | grep 'CLV-S-000' | awk '{ print $9 }' | while read smallthumbs; do
  if [ -f "/media/hakchi/customthumbs/$smallthumbs_small.png" ]; then
    cp -r "/media/hakchi/customthumbs/$smallthumbs_small.png" "/media/hakchi/${smallthumbs}/${smallthumbs}_small.png"
  fi
  if [ -f "$rootfs/customthumbs/${smallthumbs}_small.png" ]; then
    cp -r "$rootfs/customthumbs/${smallthumbs}_small.png" "/var/lib/hakchi/rootfs/usr/share/games/${smallthumbs}/${smallthumbs}_small.png"
  fi
done < /dev/stdin



